name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Testy Westy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.8
    
      - name: Setup Pipenv
        run: |
          python3 -m pip install pipenv

      - name: Install deps
        run: |
          pipenv install

      # - name: Lint
      #   run: |
      #     pipenv run lint

      - name: Check formatting
        run: |
          DIFF_LINES=$(pipenv run format | wc -l)
          exit $DIFF_LINES

      - name: Run tests
        run: |
          pipenv run test